CUDA_VISIBLE_DEVICES=0 python main.py \
    --dataset mind_data \
    --data_dir data/ref/mind \
    --model_name mlp_projector \
    --loss lm \
    --batch_size 8 \
    --num_workers 8 \
    --precision bf16 \
    --accelerator gpu \
    --devices 1 \
    --llm_path ./llama2-7b-hf \
    --rec_model_path ./SASRec.pth \
    --prompt_path ./prompt/news.txt \
    --ckpt_dir ./checkpoints/mind_ranking/ \
    --log_dir mind_ranking_logs \
    --output_dir ./output/mind_ranking/ \
    --rec_embed SASRec \
    --llm_tuning lora \
    --lora_r 4 \
    --lora_alpha 16 \
    --lora_dropout 0.1 \
    --mode test \
    --ckpt_path ./checkpoints/mind_ranking/last.ckpt

