CUDA_VISIBLE_DEVICES=0 python main.py \
    --dataset mind_data \
    --data_dir data/ref/mind \
    --model_name mlp_projector \
    --loss lm \
    --batch_size 1 \
    --num_workers 0 \
    --lr 1e-3 \
    --accumulate_grad_batches 128 \
    --max_epochs 10 \
    --check_val_every_n_epoch 1 \
    --precision bf16 \
    --accelerator gpu \
    --devices 1 \
    --llm_path ./llama2-7b-hf \
    --rec_model_path ./SASRec.pth \
    --prompt_path ./prompt/news.txt \
    --ckpt_dir ./checkpoints/mind_ranking/ \
    --log_dir mind_ranking_logs \
    --output_dir ./output/mind_ranking/ \
    --rec_embed SASRec \
    --llm_tuning lora \
    --lora_r 4 \
    --lora_alpha 16 \
    --lora_dropout 0.1 \
    --mode train

